# .streamlit/secrets.toml
SUPABASE_URL = "https://lzxawfkcwztxcbxrgvfa.supabase.co"
SUPABASE_KEY = "sb_publishable_dVaD9F566J_Yz3nOdIIDnA_8qUkFVRU"
GEMINI_KEY = "AIzaSyChFOZgsJrID1141oRbwK3FkGSpxkW0gAQ"
